#!/usr/bin/env python3
"""
Convert Audio2Face SDK geometry data to animated USD file.

This script reads geometry data generated by a2f-wrapper.exe and converts it
to an animated USD file by applying the geometry to a character USD mesh.
"""

import sys
import struct
from pathlib import Path
from typing import List, Tuple

# Configure UTF-8 encoding for Windows console
if sys.platform == "win32":
    try:
        if hasattr(sys.stdout, "reconfigure"):
            sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        if hasattr(sys.stderr, "reconfigure"):
            sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass

def read_geometry_file(geometry_file: Path) -> Tuple[int, int, int, float, List[int], List[List[float]], List[List[float]]]:
    """
    Read geometry data from binary file.
    
    Returns:
        (frame_count, skin_size, tongue_size, fps, timestamps, skin_frames, tongue_frames)
    """
    with open(geometry_file, 'rb') as f:
        # Read header
        frame_count = struct.unpack('I', f.read(4))[0]
        skin_size = struct.unpack('I', f.read(4))[0]
        tongue_size = struct.unpack('I', f.read(4))[0]
        fps = struct.unpack('f', f.read(4))[0]
        
        # Read timestamps
        timestamps = []
        for _ in range(frame_count):
            ts = struct.unpack('Q', f.read(8))[0]  # timestamp_t is uint64_t
            timestamps.append(ts)
        
        # Read skin geometry frames
        skin_frames = []
        for _ in range(frame_count):
            frame_data = struct.unpack(f'{skin_size}f', f.read(skin_size * 4))
            skin_frames.append(list(frame_data))
        
        # Read tongue geometry frames
        tongue_frames = []
        for _ in range(frame_count):
            frame_data = struct.unpack(f'{tongue_size}f', f.read(tongue_size * 4))
            tongue_frames.append(list(frame_data))
        
        return frame_count, skin_size, tongue_size, fps, timestamps, skin_frames, tongue_frames


def convert_to_usd(
    geometry_file: Path,
    character_usd: Path,
    output_usd: Path
) -> Path:
    """
    Convert geometry data to animated USD file.
    
    Args:
        geometry_file: Path to binary geometry file
        character_usd: Path to input character USD file
        output_usd: Path for output animated USD file
    
    Returns:
        Path to created USD file
    """
    try:
        from pxr import Usd, UsdGeom, Gf, Sdf, Vt
    except ImportError:
        raise ImportError(
            "USD Python API (pxr) not available. "
            "Install via: pip install usd-core"
        )
    
    print(f"Reading geometry data from: {geometry_file}")
    frame_count, skin_size, tongue_size, fps, timestamps, skin_frames, tongue_frames = read_geometry_file(geometry_file)
    
    print(f"Geometry data:")
    print(f"  Frames: {frame_count}")
    print(f"  Skin geometry size: {skin_size}")
    print(f"  Tongue geometry size: {tongue_size}")
    print(f"  FPS: {fps}")
    
    # Load character USD
    print(f"\nLoading character USD: {character_usd}")
    stage = Usd.Stage.Open(str(character_usd))
    if not stage:
        raise RuntimeError(f"Failed to open character USD file: {character_usd}")
    
    # Find mesh prim (usually /FaceMesh or similar)
    mesh_prim = None
    for prim in stage.Traverse():
        if prim.IsA(UsdGeom.Mesh):
            mesh_prim = prim
            break
    
    if not mesh_prim:
        # Create a new mesh if none exists
        print("No mesh found in character USD, creating new mesh...")
        mesh_prim = UsdGeom.Mesh.Define(stage, '/FaceMesh')
    else:
        print(f"Found mesh: {mesh_prim.GetPath()}")
    
    mesh = UsdGeom.Mesh(mesh_prim)
    
    # Get existing points to determine topology
    points_attr = mesh.GetPointsAttr()
    if points_attr:
        existing_points = points_attr.Get()
        num_vertices = len(existing_points)
        print(f"Character mesh has {num_vertices} vertices")
    else:
        # If no points, we need to create them from geometry
        # For now, assume skin_size is 3 * num_vertices (x, y, z per vertex)
        num_vertices = skin_size // 3
        print(f"Creating new mesh with {num_vertices} vertices from geometry")
        existing_points = None
    
    # Set time codes per frame
    time_codes = []
    for i, ts in enumerate(timestamps):
        # Convert timestamp to time code (assuming microseconds)
        # Time code = timestamp / (1e6 * fps) for frame number
        frame_number = i
        time_code = frame_number / fps
        time_codes.append(time_code)
    
    # Apply geometry as time-sampled points
    print(f"\nApplying {frame_count} frames of animation...")
    
    # Convert skin geometry to points
    # Skin geometry is typically stored as [x1, y1, z1, x2, y2, z2, ...]
    time_samples = {}
    
    for frame_idx, skin_frame in enumerate(skin_frames):
        if len(skin_frame) != skin_size:
            print(f"Warning: Frame {frame_idx} has incorrect size: {len(skin_frame)} != {skin_size}")
            continue
        
        # Convert to points (assuming skin_size is 3 * num_vertices)
        if skin_size % 3 != 0:
            raise RuntimeError(f"Skin geometry size ({skin_size}) is not divisible by 3")
        
        num_verts = skin_size // 3
        points = []
        for i in range(num_verts):
            x = skin_frame[i * 3]
            y = skin_frame[i * 3 + 1]
            z = skin_frame[i * 3 + 2]
            points.append(Gf.Vec3f(x, y, z))
        
        time_code = time_codes[frame_idx]
        time_samples[time_code] = Vt.Vec3fArray(points)
    
    # Set time-sampled points
    if time_samples:
        points_attr = mesh.GetPointsAttr()
        for time_code, points_array in sorted(time_samples.items()):
            points_attr.Set(points_array, Usd.TimeCode(time_code))
        
        print(f"Set {len(time_samples)} time samples")
    
    # Save output USD
    print(f"\nSaving animated USD to: {output_usd}")
    output_usd.parent.mkdir(parents=True, exist_ok=True)
    stage.GetRootLayer().Export(str(output_usd))
    
    print("Conversion complete!")
    return output_usd


def main():
    """Main entry point."""
    if len(sys.argv) != 4:
        print("Usage: convert_a2f_geometry_to_usd.py <geometry_file> <character_usd> <output_usd>")
        sys.exit(1)
    
    geometry_file = Path(sys.argv[1])
    character_usd = Path(sys.argv[2])
    output_usd = Path(sys.argv[3])
    
    if not geometry_file.exists():
        print(f"Error: Geometry file not found: {geometry_file}")
        sys.exit(1)
    
    if not character_usd.exists():
        print(f"Error: Character USD file not found: {character_usd}")
        sys.exit(1)
    
    try:
        result_usd = convert_to_usd(geometry_file, character_usd, output_usd)
        print(f"\nSuccess! Animated USD saved to: {result_usd}")
    except Exception as e:
        print(f"\nError: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()

