"""
Interactive script to set up API keys for The Talking Heads.

This script helps you configure API keys either via:
1. Environment variables (.env file)
2. Directly in config/config.yaml
"""

import os
import sys
from pathlib import Path
import yaml

# Handle Windows Unicode encoding
if sys.platform == "win32":
    try:
        if hasattr(sys.stdout, "reconfigure"):
            sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        if hasattr(sys.stderr, "reconfigure"):
            sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass

# ASCII-safe symbols for Windows
CHECK = "[OK]"
CROSS = "[X]"
WARN = "[!]"
BULLET = "*"

def get_api_key_info():
    """Display information about where to get API keys."""
    print("\n" + "=" * 60)
    print("API KEY SETUP GUIDE")
    print("=" * 60)
    print("\nYou need API keys for avatar generation and text-to-speech.")
    print("\n1. AVATAR GENERATION (choose one):")
    print("   * HeyGen: https://www.heygen.com")
    print("     - Sign up for an account")
    print("     - Go to Settings > API Keys")
    print("     - Create a new API key")
    print("\n   * D-ID (Alternative): https://www.d-id.com")
    print("     - Sign up for an account")
    print("     - Go to API section")
    print("     - Generate API key")
    
    print("\n2. TEXT-TO-SPEECH (choose one):")
    print("   * ElevenLabs (Recommended): https://elevenlabs.io")
    print("     - Sign up for an account")
    print("     - Go to Profile > API Keys")
    print("     - Copy your API key")
    print("\n   * Azure Speech Service (Alternative):")
    print("     - Azure Portal: https://portal.azure.com")
    print("     - Create a Speech Service resource")
    print("     - Get key and region from resource")
    
    print("\n3. FREE OPTIONS:")
    print("   * gTTS (Google Text-to-Speech) - No API key needed!")
    print("     - Automatically used as fallback if no keys provided")
    print("     - Limited quality but works for testing")
    
    print("\n" + "=" * 60)

def setup_env_file():
    """Set up .env file with API keys."""
    env_path = Path(".env")
    env_example_path = Path(".env.example")
    
    if env_path.exists():
        response = input("\n.env file already exists. Overwrite? (y/N): ").strip().lower()
        if response != 'y':
            print("Keeping existing .env file.")
            return
    
    print("\nSetting up .env file...")
    print("(Press Enter to skip any key you don't have)")
    
    keys = {}
    
    # Avatar keys
    print("\n--- Avatar Generation ---")
    heygen_key = input("HeyGen API Key (optional): ").strip()
    if heygen_key:
        keys["HEYGEN_API_KEY"] = heygen_key
    
    did_key = input("D-ID API Key (optional): ").strip()
    if did_key:
        keys["DID_API_KEY"] = did_key
    
    # TTS keys
    print("\n--- Text-to-Speech ---")
    elevenlabs_key = input("ElevenLabs API Key (optional): ").strip()
    if elevenlabs_key:
        keys["ELEVENLABS_API_KEY"] = elevenlabs_key
    
    azure_key = input("Azure Speech Key (optional): ").strip()
    if azure_key:
        keys["AZURE_SPEECH_KEY"] = azure_key
        azure_region = input("Azure Speech Region (optional): ").strip()
        if azure_region:
            keys["AZURE_SPEECH_REGION"] = azure_region
    
    # Write .env file
    if keys:
        with open(env_path, "w", encoding="utf-8") as f:
            f.write("# The Talking Heads - Environment Variables\n")
            f.write("# Generated by setup_api_keys.py\n\n")
            for key, value in keys.items():
                f.write(f"{key}={value}\n")
        
        print(f"\n{CHECK} Created .env file with {len(keys)} API key(s)")
        print(f"  Location: {env_path.absolute()}")
    else:
        print(f"\n{WARN} No API keys provided. Creating empty .env file.")
        print("  You can edit it later or use config/config.yaml")
        env_path.write_text("# The Talking Heads - Environment Variables\n# Add your API keys here\n", encoding="utf-8")
    
    return len(keys) > 0

def setup_config_yaml():
    """Set up API keys directly in config.yaml."""
    config_path = Path("config/config.yaml")
    
    if not config_path.exists():
        print(f"Error: {config_path} not found!")
        return False
    
    print("\nSetting up config/config.yaml...")
    print("(Press Enter to skip any key you don't have)")
    
    # Load existing config
    with open(config_path, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f) or {}
    
    if "api" not in config:
        config["api"] = {}
    
    # Avatar keys
    print("\n--- Avatar Generation ---")
    heygen_key = input("HeyGen API Key (optional): ").strip()
    if heygen_key:
        if "heygen" not in config["api"]:
            config["api"]["heygen"] = {}
        config["api"]["heygen"]["api_key"] = heygen_key
    
    did_key = input("D-ID API Key (optional): ").strip()
    if did_key:
        if "did" not in config["api"]:
            config["api"]["did"] = {}
        config["api"]["did"]["api_key"] = did_key
    
    # TTS keys
    print("\n--- Text-to-Speech ---")
    elevenlabs_key = input("ElevenLabs API Key (optional): ").strip()
    if elevenlabs_key:
        if "elevenlabs" not in config["api"]:
            config["api"]["elevenlabs"] = {}
        config["api"]["elevenlabs"]["api_key"] = elevenlabs_key
    
    azure_key = input("Azure Speech Key (optional): ").strip()
    if azure_key:
        if "azure" not in config["api"]:
            config["api"]["azure"] = {}
        config["api"]["azure"]["speech_key"] = azure_key
        azure_region = input("Azure Speech Region (optional): ").strip()
        if azure_region:
            config["api"]["azure"]["speech_region"] = azure_region
    
    # Save config
    with open(config_path, "w", encoding="utf-8") as f:
        yaml.dump(config, f, default_flow_style=False, sort_keys=False, allow_unicode=True)
    
    print(f"\n{CHECK} Updated {config_path}")
    return True

def verify_keys():
    """Verify that API keys are configured."""
    print("\n" + "=" * 60)
    print("VERIFYING API KEYS")
    print("=" * 60)
    
    # Check environment variables
    env_keys = {
        "HEYGEN_API_KEY": os.getenv("HEYGEN_API_KEY"),
        "DID_API_KEY": os.getenv("DID_API_KEY"),
        "ELEVENLABS_API_KEY": os.getenv("ELEVENLABS_API_KEY"),
        "AZURE_SPEECH_KEY": os.getenv("AZURE_SPEECH_KEY"),
    }
    
    # Check config.yaml
    config_path = Path("config/config.yaml")
    config_keys = {}
    if config_path.exists():
        try:
            with open(config_path, "r", encoding="utf-8") as f:
                config = yaml.safe_load(f) or {}
                api_config = config.get("api", {})
                
                config_keys = {
                    "HeyGen": api_config.get("heygen", {}).get("api_key"),
                    "D-ID": api_config.get("did", {}).get("api_key"),
                    "ElevenLabs": api_config.get("elevenlabs", {}).get("api_key"),
                    "Azure Speech": api_config.get("azure", {}).get("speech_key"),
                }
        except Exception as e:
            print(f"{WARN} Error reading config.yaml: {e}")
    
    # Report status
    print("\nEnvironment Variables:")
    for key, value in env_keys.items():
        status = f"{CHECK} Set" if value else f"{CROSS} Not set"
        print(f"  {key}: {status}")
    
    print("\nconfig/config.yaml:")
    for key, value in config_keys.items():
        status = f"{CHECK} Set" if value else f"{CROSS} Not set"
        print(f"  {key}: {status}")
    
    # Check if we have minimum required keys
    has_avatar = bool(env_keys["HEYGEN_API_KEY"] or env_keys["DID_API_KEY"] or 
                     config_keys["HeyGen"] or config_keys["D-ID"])
    has_tts = bool(env_keys["ELEVENLABS_API_KEY"] or env_keys["AZURE_SPEECH_KEY"] or
                  config_keys["ElevenLabs"] or config_keys["Azure Speech"])
    
    print("\n" + "=" * 60)
    if has_avatar and has_tts:
        print(f"{CHECK} Ready to generate podcasts!")
        print("  You have both avatar and TTS keys configured.")
    elif has_avatar:
        print(f"{WARN} Missing TTS key")
        print("  You have avatar keys but no TTS key.")
        print("  gTTS will be used as fallback (lower quality).")
    elif has_tts:
        print(f"{WARN} Missing Avatar key")
        print("  You have TTS keys but no avatar key.")
        print("  Avatar generation will fail without a key.")
    else:
        print(f"{WARN} No API keys configured")
        print("  You need at least:")
        print("  - One avatar key (HeyGen or D-ID)")
        print("  - One TTS key (ElevenLabs or Azure)")
        print("  Or use gTTS (free, no key needed) for TTS")
    
    print("=" * 60)

def main():
    """Main setup function."""
    print("=" * 60)
    print("The Talking Heads - API Key Setup")
    print("=" * 60)
    
    # Show info
    get_api_key_info()
    
    # Choose setup method
    print("\nHow would you like to set up your API keys?")
    print("1. Use .env file (recommended - keeps keys out of git)")
    print("2. Set in config/config.yaml (direct configuration)")
    print("3. Just verify existing keys")
    print("4. Exit")
    
    choice = input("\nEnter choice (1-4): ").strip()
    
    if choice == "1":
        setup_env_file()
        verify_keys()
    elif choice == "2":
        setup_config_yaml()
        verify_keys()
    elif choice == "3":
        verify_keys()
    elif choice == "4":
        print("\nExiting. You can run this script again anytime.")
        return 0
    else:
        print("\nInvalid choice. Exiting.")
        return 1
    
    print("\n" + "=" * 60)
    print("SETUP COMPLETE")
    print("=" * 60)
    print("\nNext steps:")
    print("1. Test your setup: python scripts/generate_real_output.py")
    print("2. Or use the CLI: python -m src.cli.main create scripts/test_episode.txt")
    print("\nFor help, see START_HERE.md")
    
    return 0

if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(1)
    except Exception as e:
        print(f"\nError: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

